### ISSUE TITLE
UX review

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/ckanext-validation#14]
### Description

On a first instance, @smth will go through:

1. Report page in resources (See #6)
2. Dataset creation process with synchronous validation enabled 

Check what can be improved: error messages, report displayed, upload steps, etc Do the necessary changes. Related issues are #11 and #10 to keep in mind the overall expected workflow.

### Tasks

- [ ] Review report page
- [ ] Review dataset creation and resource validation
- [ ] Improvements based on review

### Estimate

4

**Comment by amercader** [comment]
@smth to confirm estimate

**Comment by smth** [comment]
Without knowing much about 2., I've looked at 1., and there are a couple of things that I think could be improved:
- Make it easier to see the problematic parts of a table (i.e remove the need to horizontal scroll)
- Make the warning / alert more useful at a glance / without clicking

In terms of making the changes, I think this should take the form of moving to the latest report design (that I have been working on for Goodtables). I have taken the example from #6 and put the data in the new design here http://p.smth.uk/goodtables/ui/report Notable difference here is that the tables are truncated, to just show the errors. I plan to add a way of viewing a non truncated / scrollable version too, but thought worth sharing at this stage.

**Comment by amercader** [comment]
@smth comments and individual issues:

https://trello-attachments.s3.amazonaws.com/59c11e721297d410fdf95061/59c38af8c1dd5d1965941d88/1fbb6d84c1775c213980723ab32ec9b2/validation.pdf

https://trello-attachments.s3.amazonaws.com/59c11e721297d410fdf95061/59c38af8c1dd5d1965941d88/a299e1cc74d19947720076dae04d775a/error.pdf

https://trello-attachments.s3.amazonaws.com/59c11e721297d410fdf95061/59c38af8c1dd5d1965941d88/c382feed6c14fd99253f366ef332faaf/report.pdf

* Validation options field: #19
* Confusing error message: #20
* Report popup width: #21

**Comment by amercader** [comment]
All three issues addressed.

**Comment by amercader** [comment]
Most of the different features and functionality around data validation is already in place, but they lack cohesion and the whole UX could be improved. This should be done with someone with frontend and UX experience, but some example points:

    

- The Data Schema field feels disconnected from the file upload one, perhaps they should be closer
-Is not easy to see that the "Infer" button appears when a file is uploaded
- "Infer" itself is quite a vague term, maybe "Editor"
- Validation options it's a quite advanced field but it takes up a lot of space, perhaps it could be hidden by default under an "Advance" section
- The whole validation features only apply to tabular files. Should the schema and validation options fields be only shown if the file is csv or excel?
