### ISSUE TITLE
User testing

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/ckanext-validation#15]
### Description

Perform user testing by external users, collection of feedback and implementation of changes if needed. We need to prepare tasks, questions etc (@vitorbaptista can help with his experience on OT user testing)

### Tasks

- [ ] Prepare testing materials
- [ ] Collect feedback, triage and create issues
- [ ] Implement changes based on review

### Estimate

4

**Comment by s-chand** [comment]
Hey @amercader So I'm using this plugin on a project. I was already writing one myself (ckan-validator) using goodtables but stopped immediately I stumbled on ckanext-validation.
so i'll be extending this to support some of my project's requirements.

For example, doing something with the file (e.g pushing the file through logstash) if validation is successful. etc

This is a fantastic effort and you have my full support in closing some issues :)

**Comment by Stephen-Gates** [comment]
Happy to help with user testing. I think CKAN Validation, CKAN Data Packager and Data Curator could be a great combo, especially since the Schema Editor is in the backlog. 

Read more about how the combo could work together at https://github.com/frictionlessdata/ckanext-datapackager/issues/63#issuecomment-354960478 

I'm wondering:

- if some of the changes proposed there should wait for work to be done here?
- if, as you recommend CKAN Scheming, if there is a schema defined for data packages and resources?

Anyway, let me know when you want something tested.
